// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Sample {
    squadName:  string;
    homeTown:   string;
    formed:     number;
    secretBase: string;
    active:     boolean;
    members:    Member[];
}

export interface Member {
    name:           string;
    age:            number;
    secretIdentity: string;
    powers:         string[];
}
